name: deploy-solution-to-prod

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Power Platform Tools (PAC)
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Fetch the ready-to-ship solution from GitHub artifact store
        uses: actions/download-artifact@v4
        with:
          name: managedSolutions
          path: out/release/

      - name: List downloaded files
        run: Get-ChildItem -Recurse .\out\release\

      - name: Import solution as Managed to production environment
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://org8e5dc8f7.crm.dynamics.com'
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: 'out/release/GitHubActionsGitHubDemo.zip'
          force-overwrite: true
          publish-changes: true
